=== stake-house/wagyu-key-gen/src/vendors/valefar-staking-deposit-cli/tests/test_intl/schemas/credentials.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "object",
    "properties": {
        "from_mnemonic": {
            "type": "object",
            "properties": {
                "msg_key_creation": {
                    "type": "string"
                }
            },
            "required": [
                "msg_key_creation"
            ]
        },
        "export_keystores": {
            "type": "object",
            "properties": {
                "msg_keystore_creation": {
                    "type": "string"
                }
            },
            "required": [
                "msg_keystore_creation"
            ]
        },
        "export_deposit_data_json": {
            "type": "object",
            "properties": {
                "msg_depositdata_creation": {
                    "type": "string"
                }
            },
            "required": [
                "msg_depositdata_creation"
            ]
        },
        "verify_keystores": {
            "type": "object",
            "properties": {
                "msg_keystore_verification": {
                    "type": "string"
                }
            },
            "required": [
                "msg_keystore_verification"
            ]
        }
    },
    "required": [
        "from_mnemonic",
        "export_keystores",
        "export_deposit_data_json",
        "verify_keystores"
    ]
}

=== stake-house/wagyu-key-gen/src/vendors/valefar-staking-deposit-cli/staking_deposit/intl/tr/credentials.json
{
    "from_mnemonic": {
        "msg_key_creation": "Anahtarlarınız oluşturuluyor:\t\t"
    },
    "export_keystores": {
        "msg_keystore_creation": "Anahtar depolarınız oluşturuluyor:\t"
    },
    "export_deposit_data_json": {
        "msg_depositdata_creation": "Depozito veriniz (depositdata) oluşturuluyor:\t"
    },
    "verify_keystores": {
        "msg_keystore_verification": "Anahtar depolarınız doğrulanıyor:\t"
    }
}

=== stake-house/wagyu-key-gen/src/vendors/valefar-staking-deposit-cli/staking_deposit/intl/zh-CN/credentials.json
{
    "from_mnemonic": {
        "msg_key_creation": "正在创建您的密钥：\t\t"
    },
    "export_keystores": {
        "msg_keystore_creation": "正在创建您的密钥库：\t"
    },
    "export_deposit_data_json": {
        "msg_depositdata_creation": "正在创建您的存款数据："
    },
    "verify_keystores": {
        "msg_keystore_verification": "正在验证您的密钥库："
    }
}

=== stake-house/wagyu-key-gen/src/vendors/valefar-staking-deposit-cli/staking_deposit/intl/fr/credentials.json
{
    "from_mnemonic": {
        "msg_key_creation": "Création de vos clés :\t\t"
    },
    "export_keystores": {
        "msg_keystore_creation": "Création de vos keystores :\t"
    },
    "export_deposit_data_json": {
        "msg_depositdata_creation": "Création de vos données de dépôt :\t"
    },
    "verify_keystores": {
        "msg_keystore_verification": "Vérification de vos keystores :\t"
    }
}
