=== stake-house/wagyu-key-gen/src/vendors/valefar-staking-deposit-cli/tests/test_intl/schemas/credentials.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "object",
    "properties": {
        "from_mnemonic": {
            "type": "object",
            "properties": {
                "msg_key_creation": {
                    "type": "string"
                }
            },
            "required": [
                "msg_key_creation"
            ]
        },
        "export_keystores": {
            "type": "object",
            "properties": {
                "msg_keystore_creation": {
                    "type": "string"
                }
            },
            "required": [
                "msg_keystore_creation"
            ]
        },
        "export_deposit_data_json": {
            "type": "object",
            "properties": {
                "msg_depositdata_creation": {
                    "type": "string"
                }
            },
            "required": [
                "msg_depositdata_creation"
            ]
        },
        "verify_keystores": {
            "type": "object",
            "properties": {
                "msg_keystore_verification": {
                    "type": "string"
                }
            },
            "required": [
                "msg_keystore_verification"
            ]
        }
    },
    "required": [
        "from_mnemonic",
        "export_keystores",
        "export_deposit_data_json",
        "verify_keystores"
    ]
}

=== stake-house/wagyu-key-gen/src/vendors/valefar-staking-deposit-cli/staking_deposit/intl/ro/credentials.json
{
    "from_mnemonic": {
        "msg_key_creation": "Se creează cheile:\t\t"
    },
    "export_keystores": {
        "msg_keystore_creation": "Se creează depozitele de chei:\t"
    },
    "export_deposit_data_json": {
        "msg_depositdata_creation": "Se creează datele de depozit:\t"
    },
    "verify_keystores": {
        "msg_keystore_verification": "Se verifică depozitele de chei:\t"
    }
}

=== stake-house/wagyu-key-gen/src/vendors/valefar-staking-deposit-cli/staking_deposit/intl/id/credentials.json
{
    "from_mnemonic": {
        "msg_key_creation": "Membuat kunci Anda:\t\t"
    },
    "export_keystores": {
        "msg_keystore_creation": "Membuat keystore Anda:\t"
    },
    "export_deposit_data_json": {
        "msg_depositdata_creation": "Membuat depositdata Anda:\t"
    },
    "verify_keystores": {
        "msg_keystore_verification": "Memverifikasi keystore Anda:\t"
    }
}

=== stake-house/wagyu-key-gen/src/vendors/valefar-staking-deposit-cli/staking_deposit/intl/ar/credentials.json
{
    "from_mnemonic": {
        "msg_key_creation": "إنشاء المفاتيح الخاصة بك:\t\t"
    },
    "export_keystores": {
        "msg_keystore_creation": "إنشاء متاجر المفاتيح الخاصة بك:\t"
    },
    "export_deposit_data_json": {
        "msg_depositdata_creation": "إنشاء بيانات الإيداع الخاصة بك:\t"
    },
    "verify_keystores": {
        "msg_keystore_verification": "التحقق من متاجر المفاتيح الخاصة بك:\t"
    }
}

=== stake-house/wagyu-key-gen/src/vendors/valefar-staking-deposit-cli/staking_deposit/intl/pt-BR/credentials.json
{
    "from_mnemonic": {
        "msg_key_creation": "Criação das suas chaves:\t\t"
    },
    "export_keystores": {
        "msg_keystore_creation": "Criação dos seus keystores:\t"
    },
    "export_deposit_data_json": {
        "msg_depositdata_creation": "Criação dos seus dados de depósito:\t"
    },
    "verify_keystores": {
        "msg_keystore_verification": "Verificação dos seus keystores:\t"
    }
}

=== stake-house/wagyu-key-gen/src/vendors/valefar-staking-deposit-cli/staking_deposit/intl/ko/credentials.json
{
    "from_mnemonic": {
        "msg_key_creation": "키 생성 중:\t\t"
    },
    "export_keystores": {
        "msg_keystore_creation": "키스토어 생성 중:\t"
    },
    "export_deposit_data_json": {
        "msg_depositdata_creation": "예치금 데이터 생성 중:\t"
    },
    "verify_keystores": {
        "msg_keystore_verification": "키스토어 검증 중:\t"
    }
}

=== stake-house/wagyu-key-gen/src/vendors/valefar-staking-deposit-cli/staking_deposit/intl/it/credentials.json
{
    "from_mnemonic": {
        "msg_key_creation": "Creazione delle tue chiavi:\t\t"
    },
    "export_keystores": {
        "msg_keystore_creation": "Creazione dei tuoi archivi chiavi:\t"
    },
    "export_deposit_data_json": {
        "msg_depositdata_creation": "Creazione dei tuoi dati di deposito:\t"
    },
    "verify_keystores": {
        "msg_keystore_verification": "Verifica dei tuoi archivi chiavi:\t"
    }
}

=== stake-house/wagyu-key-gen/src/vendors/valefar-staking-deposit-cli/staking_deposit/intl/ja/credentials.json
{
    "from_mnemonic": {
        "msg_key_creation": "キーを作成しています:\t\t"
    },
    "export_keystores": {
        "msg_keystore_creation": "キーストアを作成しています:\t"
    },
    "export_deposit_data_json": {
        "msg_depositdata_creation": "デポジットデータを作成しています:\t"
    },
    "verify_keystores": {
        "msg_keystore_verification": "キーストアを確認しています:\t"
    }
}

=== stake-house/wagyu-key-gen/src/vendors/valefar-staking-deposit-cli/staking_deposit/intl/el/credentials.json
{
    "from_mnemonic": {
        "msg_key_creation": "Δημιουργώντας τα κλειδιά σας:\t\t"
    },
    "export_keystores": {
        "msg_keystore_creation": "Δημιουργώντας τους χώρους αποθήκευσης των κλειδιών σας:\t"
    },
    "export_deposit_data_json": {
        "msg_depositdata_creation": "Δημιουργώντας τα δεδομένα κατάθεσής σας:\t"
    },
    "verify_keystores": {
        "msg_keystore_verification": "Δημιουργώντας τους χώρους αποθήκευσης των κλειδιών σας:\t"
    }
}
